### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by yuanlizhanshi** [Jason-Teng/MethGET#1]
`python ~/Desktop/wgbs/methyget/preprocess.py -s sample_list.txt -g Bomo_gene_models.gtf`
save the information of gene annotation: big_bed
Total gene number is 16880
save Gene_Body_Bed
save Promoter_Bed
save exon bed
save intron bed
Traceback (most recent call last):
  File "/home/kyh/Desktop/wgbs/methyget/preprocess.py", line 407, in <module>
    main()
  File "/home/kyh/Desktop/wgbs/methyget/preprocess.py", line 399, in main
    WholeProcess(Samplelist.iloc[i,0],Samplelist.iloc[i,1],args.cutoff, Samplelist.iloc[i,2], gb_bed, pmt_bed, exon_bed, intron_bed) # preprocess each methylome
  File "/home/kyh/miniconda3/envs/py2/lib/python2.7/site-packages/pandas/core/indexing.py", line 1494, in __getitem__
    return self._getitem_tuple(key)
  File "/home/kyh/miniconda3/envs/py2/lib/python2.7/site-packages/pandas/core/indexing.py", line 2143, in _getitem_tuple
    self._has_valid_tuple(tup)
  File "/home/kyh/miniconda3/envs/py2/lib/python2.7/site-packages/pandas/core/indexing.py", line 223, in _has_valid_tuple
    self._validate_key(k, i)
  File "/home/kyh/miniconda3/envs/py2/lib/python2.7/site-packages/pandas/core/indexing.py", line 2070, in _validate_key
    self._validate_integer(key, axis)
  File "/home/kyh/miniconda3/envs/py2/lib/python2.7/site-packages/pandas/core/indexing.py", line 2139, in _validate_integer
    raise IndexError("single positional indexer is out-of-bounds")
IndexError: single positional indexer is out-of-bounds

**Comment by yuanlizhanshi** [comment]
Figured, my samplelist was not separated by '\t'
